=== jhliberty/AAF/Utilities/AAFAnalyzer/Requirements/AAFRequirementsFormat.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT requirement-set (requirement-set-name, requirement-set-version, requirement+)>
<!ELEMENT requirement-set-name (#PCDATA)>
<!ELEMENT requirement-set-version (#PCDATA)>
<!ELEMENT requirement (id, name, desc, annotate, note, action, ref)>
<!ATTLIST requirement
	type ( app | file | definition ) #REQUIRED
	category ( general | import-export | compositional | metadata | mixdown | auxiliary-file | annotations | effect | optional-properties | structured-storage | protocol | ad-hoc ) #REQUIRED
        action ( reconcile )
>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT annotate (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT ref (doc, version, section)>
<!ELEMENT doc (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT section (#PCDATA)>

=== jhliberty/AAF/Utilities/AAFAnalyzer/Requirements/AAFRequirements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE requirement-set SYSTEM "AAFRequirementsFormat.dtd" [
    <!ENTITY DOC_AAF_EP "AAF Edit Protocol">
    <!ENTITY VER_EP_1.0 "2005-04-08">
]>
<requirement-set>

    <requirement-set-name>Edit Protocol Compliance Requirement Set</requirement-set-name>
    <requirement-set-version>&VER_EP_1.0;</requirement-set-version>

    <requirement type="app" category="general">
        <id>REQ_EP_001</id>
        <name>Metadata Interchange</name>
        <desc>Interchange of the metadata specified in this document shall be performed in an accurate and predictable manner.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.2</section>
        </ref>
    </requirement>

    <requirement type="app" category="general">
        <id>REQ_EP_002</id>
        <name>Import Accuracy</name>
        <desc>Upon import, an Edit Protocol compliant application shall clearly report any alteration to the composition during the [import] process according to fallback behaviours that are described in this document.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.2</section>
        </ref>
    </requirement>

    <requirement type="app" category="general">
        <id>REQ_EP_003</id>
        <name>Import Unsupported Metadata</name>
        <desc>In the Edit Protocol Import/Export model an application is not required to import, maintain and subsequently export metadata objects from the AAF file that it cannot understand.  Applications shall not however replace or represent a subsequent exported file as the originally imported AAF file.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.3</section>
        </ref>
    </requirement>

    <requirement type="app" category="general">
        <id>REQ_EP_004.1</id>
        <name>Immutability of Mobs</name>
        <desc>An application shall implement the rules regarding immutability of Mobs as described in the AAF Object Specification v1.1.  These rules specify how Mobs shall be identified when they are processed by an application.  Specifically, conditions are defined in which the identification of the Mob (MobID) must change, and in which the identification of the Mob must not change.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.3</section>
        </ref>
    </requirement>

    <requirement type="file" category="general">
        <id>REQ_EP_004.2</id>
        <name>Unique MobsIDs</name>
        <desc>Two Mobs in an AAF file shall not have the same MobID.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.3</section>
        </ref>
    </requirement>

    <requirement type="app" category="general">
        <id>REQ_EP_005</id>
        <name>Log Importing Fallback Behaviour</name>
        <desc>The AAF Edit Protocol does not remove the requirement that importing applications shall log fallback behaviour for the benefit of the user as defined in this document.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.4</section>
        </ref>
    </requirement>

    <requirement type="app" category="general">
        <id>REQ_EP_006</id>
        <name>Non Edit Protocol Objects</name>
        <desc>Inclusion of extraneous data (i.e. non-Edit Protocol Objects and/or Dark Metadata) shall not invalidata, obfuscate or change the meaning of the core Edit Protocol data.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.5</section>
        </ref>
    </requirement>

    <requirement type="app" category="general">
        <id>REQ_EP_007</id>
        <name>Legacy Features</name>
        <desc>Support for legacy features is not required for compliance with the AAF Edit Protocol</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>4.2.6</section>
        </ref>
    </requirement>

    <requirement type="app" category="import-export">
        <id>REQ_EP_008</id>
        <name>Application Crash</name>
        <desc>An application shall not lock-up, crash or give-up on exporting or importing an AAF file.  When an action is likely to take a considerable amount of time, an indication of this should be provided.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>5</section>
        </ref>
    </requirement>

    <requirement type="app" category="import-export">
        <id>REQ_EP_009</id>
        <name>Import Fallback</name>
        <desc>Where the feature set of an application is insufficient to completely or accurately import the AAF file, an application shall observe the fallback behaviours specified throughout the AAF Edit Protocol.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>5</section>
        </ref>
    </requirement>

    <requirement type="app" category="import-export">
        <id>REQ_EP_010</id>
        <name>Diagnostic Log</name>
        <desc>An application shall provide a mechanism to log diagnostic information for each import or export operation.  The log may be temporary, but shall be avaliable to an expert user.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>5</section>
        </ref>
    </requirement>

    <requirement type="app" category="import-export">
        <id>REQ_EP_011</id>
        <name>Log Details</name>
        <desc>Certain fallback behaviours shall be logged, as defined in the AAF Edit Protocol.  Wherever appropriate, the diagnostic log should identify the Mob, Track and Position at which the fallback behaviour was required.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>5</section>
        </ref>
    </requirement>

    <requirement type="app" category="import-export">
        <id>REQ_EP_012</id>
        <name>Exporting Disallowed Metadata</name>
        <desc>Where the feature set of an exporting application supports program metadata that the Edit Protocol specifically disallows (e.g. a program consisting of different audio sample rates which is disallowed in Section 7.3), the application shall not export that metadata to an Edit Protocol AAF file.  The omission of any metadata on export in order to comply with the Edit Protocol should be logged.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>5</section>
        </ref>
    </requirement>

    <requirement type="file" category="compositional">
        <id>REQ_EP_013</id>
        <name>Export Clip Method</name>
        <desc>An application shall export each clip using one of the methods described in Section 6.1 of the AAF Edit Protocol.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>6.1</section>
        </ref>
    </requirement>

    <requirement type="file" category="compositional">
        <id>REQ_EP_014</id>
        <name>Import Clip Method</name>
        <desc>An application shall import clips that use any of the methods described in Section 6.1 of the AAF Edit Protocol.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>6.1</section>
        </ref>
    </requirement>

    <requirement type="app" category="compositional">
        <id>REQ_EP_015</id>
        <name>Import non-Exported Data</name>
        <desc>An application that exports file source material is required to gracefully import material that does not contain it; an application that does not export file source material is required to gracefully import material that contains it.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>6.1</section>
        </ref>
    </requirement>

    <requirement type="app" category="compositional">
        <id>REQ_EP_016</id>
        <name>Export Mobs for Entire Derivation Chain</name>
        <desc>An exporting application should include and reference the Mobs for the entire derivation chain to the extent that it is aware of it.</desc>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>6.2</section>
        </ref>
    </requirement>

    <requirement type="file" category="compositional" action="reconcile">
        <id>REQ_EP_017</id>
        <name>End of Derivation Chain</name>
        <desc>The end of the derivation change (i.e. the original material), to the extent an application is aware of it, shall be specified using a zero-value SourceClip object.</desc>
	<annotate>Template Clip, Import Source, File Source, Tape Source, File Source, and Recording Source may terminate with zero-value Sourceclip object.</annotate>
	<note>The spec needs to be explicit, hence the annotation. It is not just SourceMob that can zero-terminate. A template clip (Master Mob) can also do so.</note>
        <ref>
            <doc>&DOC_AAF_EP;</doc>
            <version>&VER_EP_1.0;</version>
            <section>6.2</section>
        </ref>
    </requirement>

    <requirement type="file" category="compositional" action="reconcile">
        <id>REQ_EP_018</id>
        <name>Include CompositionMob or MasterMob</name>
        <desc>If a reference is made to a CompositionMob or MasterMob, that Mob shall be included in the AAF file.</desc>
