=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPDerivationChain.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % MOB "top-level | lower-level | sub-clip | adjusted-clip | template-clip | clip | file-source | recording-source | import-source | tape-source | film-source | auxiliary-source | multi-channel-audio | mono-audio | cdci-source | rgba-source">
<!ENTITY % MOB_SLOT "timeline-mob-slot | static-mob-slot | event-mob-slot">
<!ENTITY % OPERATION_GROUP "video-dissolve | smpte-video-wipe | video-speed-control | video-repeat | video-flip | video-flop | video-flip-flop | video-position | video-crop | video-scale | video-rotate | video-corner-pinning | alpha-with-video-key | separate-alpha-key | luminance-key | chroma-key | mono-audio-gain | mono-audio-pan | mono-audio-dissolve | two-parameter-mono-audio-dissolve">
<!ENTITY % SOURCE_REFERENCE "source-clip | eoc | oof">
<!ENTITY % SEGMENT "sequence | timecode | timecode-stream-12m | edgecode | comment-marker | descriptive-marker | operation-group | %SOURCE_REFERENCE; | %OPERATION_GROUP;">
<!ENTITY % COMPONENT "transition | %SEGMENT;">
<!ENTITY % COMMENTS_AND_COMPONENTS "( comment | klv-data | %COMPONENT; )*">
<!ENTITY % COMMENTS_AND_SEGMENTS "( comment | klv-data | %SEGMENT; )*">
<!ENTITY % ESSENCE_TYPE "none | audio | picture | timecode | edgecode | auxiliary">

<!ELEMENT aaf-file ( dictionary?, ( %MOB; ) )+>
<!ATTLIST aaf-file
    operational-pattern ( edit-protocol | invalid ) #IMPLIED
    effect-data-definitions ( current | legacy ) #IMPLIED >

<!-- Dictionary and Definitions -->
<!ELEMENT dictionary ( klv-data-def | tagged-value-def | operation-def )+>

<!ELEMENT klv-data-def EMPTY>
<!ATTLIST klv-data-def
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!ELEMENT tagged-value-def EMPTY>
<!ATTLIST tagged-value-def
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!ELEMENT operation-def EMPTY>
<!ATTLIST operation-def
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!-- Mobs -->

<!ELEMENT top-level ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST top-level name CDATA #IMPLIED>

<!ELEMENT lower-level ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST lower-level name CDATA #IMPLIED>

<!ELEMENT sub-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST sub-clip name CDATA #IMPLIED>

<!ELEMENT adjusted-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST adjusted-clip name CDATA #IMPLIED>

<!ELEMENT template-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST template-clip name CDATA #IMPLIED>

<!ELEMENT clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST clip name CDATA #IMPLIED>

<!ELEMENT file-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST file-source
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT multi-channel-audio ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST multi-channel-audio
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT mono-audio ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST mono-audio
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT cdci-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST cdci-source
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
    alpha-transparency ( max | min ) #IMPLIED
>

<!ELEMENT rgba-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST rgba-source
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
    alpha-transparency ( max | min ) #IMPLIED
>

<!ELEMENT recording-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST recording-source name CDATA #IMPLIED>

<!ELEMENT import-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST import-source name CDATA #IMPLIED>

<!ELEMENT tape-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST tape-source name CDATA #IMPLIED>

<!ELEMENT film-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST film-source name CDATA #IMPLIED>

<!ELEMENT auxiliary-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST auxiliary-source name CDATA #IMPLIED>

<!-- Annotations -->
<!ELEMENT comment EMPTY>
<!ATTLIST comment
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!ELEMENT klv-data EMPTY>
<!ATTLIST klv-data
    key-name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!-- Type A Components -->

<!ELEMENT timecode ( ( comment | klv-data )* )>
<!ATTLIST timecode
    track-type ( timecode ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT edgecode ( ( comment | klv-data )* )>
<!ATTLIST edgecode
    track-type ( edgecode ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT timecode-stream-12m ( ( comment | klv-data )* )>
<!ATTLIST timecode-stream-12m
    track-type ( timecode ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT eoc ( ( comment | klv-data )* )>
<!ATTLIST eoc
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT oof ( ( comment | klv-data )* )>
<!ATTLIST oof
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    start-time CDATA #IMPLIED
>

<!-- Type B Components -->

<!ELEMENT source-clip ( ( comment | klv-data )*, ( %MOB; ), ( comment | klv-data )* )>
<!ATTLIST source-clip
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    start-time CDATA #IMPLIED
>

<!-- Type C Components -->
<!ELEMENT transition ( ( comment | klv-data )*, ( %OPERATION_GROUP; | operation-group ), ( comment | klv-data )* )>
<!ATTLIST transition
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT sequence ( ( comment | klv-data )*, ( %COMPONENT; ), %COMMENTS_AND_COMPONENTS; )>
<!ATTLIST sequence
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT comment-marker ( ( comment | klv-data )*, ( %SOURCE_REFERENCE; )?, ( comment | klv-data )* )>
<!ATTLIST comment-marker
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    position CDATA #IMPLIED
>

<!ELEMENT descriptive-marker ( ( comment | klv-data )*, ( ( ( %SOURCE_REFERENCE; )?, ( comment | klv-data )*, descriptive-framework? ) | ( descriptive-framework?, ( comment | klv-data )*, ( %SOURCE_REFERENCE; )? ) ), ( comment | klv-data )* )>
<!ATTLIST descriptive-marker
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    position CDATA #IMPLIED
>

<!-- Type D components -->

<!--
    Operation Groups:
        In Specification:
            Contain 1 SourceReference (pre-rendered version)
            n Parameters
            m Segments
        In XML:
            Contain 1 Segment
-->

<!ELEMENT operation-group ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST operation-group
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    operation-definition CDATA #REQUIRED
>

<!ELEMENT video-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-dissolve
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT smpte-video-wipe ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST smpte-video-wipe
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-speed-control ( %COMMENTS_AND_COMPONENTS;, ( constant-speed-ratio | varying-speed-ratio )?, %COMMENTS_AND_COMPONENTS; )>
<!ATTLIST video-speed-control
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

    <!ELEMENT constant-speed-ratio EMPTY>
    <!ATTLIST constant-speed-ratio
        numerator CDATA #REQUIRED
        denominator CDATA #REQUIRED
    >

    <!ELEMENT varying-speed-ratio EMPTY>
    <!ATTLIST varying-speed-ratio
        numerator CDATA #REQUIRED
        denominator CDATA #REQUIRED
        interpolator ( b-spline | constant | linear | log | none | power ) #REQUIRED
    >

<!ELEMENT video-repeat ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-repeat
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-flip ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flip
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-flop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flop
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-flip-flop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flip-flop
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-position ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-position
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-crop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-crop
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-scale ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-scale
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-rotate ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-rotate
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-corner-pinning ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-corner-pinning
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT alpha-with-video-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST alpha-with-video-key
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT separate-alpha-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST separate-alpha-key
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT luminance-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST luminance-key
    track-type ( picture ) #REQUIRED
    length CDATA #REQUIRED
>

<!ELEMENT chroma-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST chroma-key
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT mono-audio-gain ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-gain
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT mono-audio-pan ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-pan
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT mono-audio-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-dissolve
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT two-parameter-mono-audio-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST two-parameter-mono-audio-dissolve
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!-- Mob Slots -->

<!ELEMENT timeline-mob-slot ( %SEGMENT; )>
<!ATTLIST timeline-mob-slot
    edit-rate-numerator CDATA #REQUIRED
    edit-rate-denominator CDATA #REQUIRED
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
    marked-in-point CDATA #IMPLIED
    marked-out-point CDATA #IMPLIED
    origin CDATA #IMPLIED
>

<!ELEMENT static-mob-slot ( %SEGMENT; )>
<!ATTLIST static-mob-slot
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!ELEMENT event-mob-slot ( %SEGMENT; )>
<!ATTLIST event-mob-slot
    edit-rate-numerator CDATA #REQUIRED
    edit-rate-denominator CDATA #REQUIRED
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!-- Other Interchange Objects -->
<!ELEMENT descriptive-framework EMPTY>

<!-- End a derivation chain on a mob -->
<!ELEMENT bad-eoc EMPTY>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPDerivationTest3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file>
<!-- The following test cases should not cause failures because they are not composition Mobs.-->
 <clip name="Initial->Clip">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <eoc length="0" track-type="none"/>
  </timeline-mob-slot>
 </clip>
 <file-source sample-rate-numerator="1" sample-rate-denominator="1" name="Initial->File Source">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <eoc length="0" track-type="none"/>
  </timeline-mob-slot>
 </file-source>
 <recording-source name="Initial->Recording Source">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <eoc length="0" track-type="none"/>
  </timeline-mob-slot>
 </recording-source>
 <import-source name="Initial->Import Source">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <eoc length="0" track-type="none"/>
  </timeline-mob-slot>
 </import-source>
 <tape-source name="Initial->Tape Source">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <eoc length="0" track-type="none"/>
  </timeline-mob-slot>
 </tape-source>
 <film-source name="Initial-Film Source">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <eoc length="0" track-type="none"/>
  </timeline-mob-slot>
 </film-source>
</aaf-file>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPEditRateTest2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file>
<!-- Test one incorrect audio edit rate -->
 <clip name="Clip 1">
  <timeline-mob-slot edit-rate-denominator="24" edit-rate-numerator="600">
   <source-clip length="0" track-type="audio">
    <file-source name="File Source 1" sample-rate-denominator="24" sample-rate-numerator="600">
     <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
      <eoc length="0" track-type="none"/>
     </timeline-mob-slot>
    </file-source>
   </source-clip>
  </timeline-mob-slot>
 </clip>
 <clip name="Clip 2">
  <timeline-mob-slot edit-rate-denominator="24" edit-rate-numerator="1200000">
   <source-clip length="0" track-type="audio">
    <file-source name="File Source 1" sample-rate-denominator="24" sample-rate-numerator="600">
     <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
      <eoc length="0" track-type="none"/>
     </timeline-mob-slot>
    </file-source>
   </source-clip>
  </timeline-mob-slot>
 </clip>
</aaf-file>
