=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPDerivationChain.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % MOB "top-level | lower-level | sub-clip | adjusted-clip | template-clip | clip | file-source | recording-source | import-source | tape-source | film-source | auxiliary-source | multi-channel-audio | mono-audio | cdci-source | rgba-source">
<!ENTITY % MOB_SLOT "timeline-mob-slot | static-mob-slot | event-mob-slot">
<!ENTITY % OPERATION_GROUP "video-dissolve | smpte-video-wipe | video-speed-control | video-repeat | video-flip | video-flop | video-flip-flop | video-position | video-crop | video-scale | video-rotate | video-corner-pinning | alpha-with-video-key | separate-alpha-key | luminance-key | chroma-key | mono-audio-gain | mono-audio-pan | mono-audio-dissolve | two-parameter-mono-audio-dissolve">
<!ENTITY % SOURCE_REFERENCE "source-clip | eoc | oof">
<!ENTITY % SEGMENT "sequence | timecode | timecode-stream-12m | edgecode | comment-marker | descriptive-marker | operation-group | %SOURCE_REFERENCE; | %OPERATION_GROUP;">
<!ENTITY % COMPONENT "transition | %SEGMENT;">
<!ENTITY % COMMENTS_AND_COMPONENTS "( comment | klv-data | %COMPONENT; )*">
<!ENTITY % COMMENTS_AND_SEGMENTS "( comment | klv-data | %SEGMENT; )*">
<!ENTITY % ESSENCE_TYPE "none | audio | picture | timecode | edgecode | auxiliary">

<!ELEMENT aaf-file ( dictionary?, ( %MOB; ) )+>
<!ATTLIST aaf-file
    operational-pattern ( edit-protocol | invalid ) #IMPLIED
    effect-data-definitions ( current | legacy ) #IMPLIED >

<!-- Dictionary and Definitions -->
<!ELEMENT dictionary ( klv-data-def | tagged-value-def | operation-def )+>

<!ELEMENT klv-data-def EMPTY>
<!ATTLIST klv-data-def
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!ELEMENT tagged-value-def EMPTY>
<!ATTLIST tagged-value-def
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!ELEMENT operation-def EMPTY>
<!ATTLIST operation-def
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!-- Mobs -->

<!ELEMENT top-level ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST top-level name CDATA #IMPLIED>

<!ELEMENT lower-level ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST lower-level name CDATA #IMPLIED>

<!ELEMENT sub-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST sub-clip name CDATA #IMPLIED>

<!ELEMENT adjusted-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST adjusted-clip name CDATA #IMPLIED>

<!ELEMENT template-clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST template-clip name CDATA #IMPLIED>

<!ELEMENT clip ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST clip name CDATA #IMPLIED>

<!ELEMENT file-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST file-source
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT multi-channel-audio ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST multi-channel-audio
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT mono-audio ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST mono-audio
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
>

<!ELEMENT cdci-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST cdci-source
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
    alpha-transparency ( max | min ) #IMPLIED
>

<!ELEMENT rgba-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST rgba-source
    name CDATA #IMPLIED
    sample-rate-numerator CDATA #REQUIRED
    sample-rate-denominator CDATA #REQUIRED
    alpha-transparency ( max | min ) #IMPLIED
>

<!ELEMENT recording-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST recording-source name CDATA #IMPLIED>

<!ELEMENT import-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST import-source name CDATA #IMPLIED>

<!ELEMENT tape-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST tape-source name CDATA #IMPLIED>

<!ELEMENT film-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST film-source name CDATA #IMPLIED>

<!ELEMENT auxiliary-source ( %MOB_SLOT; | bad-eoc )+>
<!ATTLIST auxiliary-source name CDATA #IMPLIED>

<!-- Annotations -->
<!ELEMENT comment EMPTY>
<!ATTLIST comment
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!ELEMENT klv-data EMPTY>
<!ATTLIST klv-data
    key-name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!-- Type A Components -->

<!ELEMENT timecode ( ( comment | klv-data )* )>
<!ATTLIST timecode
    track-type ( timecode ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT edgecode ( ( comment | klv-data )* )>
<!ATTLIST edgecode
    track-type ( edgecode ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT timecode-stream-12m ( ( comment | klv-data )* )>
<!ATTLIST timecode-stream-12m
    track-type ( timecode ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT eoc ( ( comment | klv-data )* )>
<!ATTLIST eoc
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT oof ( ( comment | klv-data )* )>
<!ATTLIST oof
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    start-time CDATA #IMPLIED
>

<!-- Type B Components -->

<!ELEMENT source-clip ( ( comment | klv-data )*, ( %MOB; ), ( comment | klv-data )* )>
<!ATTLIST source-clip
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    start-time CDATA #IMPLIED
>

<!-- Type C Components -->
<!ELEMENT transition ( ( comment | klv-data )*, ( %OPERATION_GROUP; | operation-group ), ( comment | klv-data )* )>
<!ATTLIST transition
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT sequence ( ( comment | klv-data )*, ( %COMPONENT; ), %COMMENTS_AND_COMPONENTS; )>
<!ATTLIST sequence
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT comment-marker ( ( comment | klv-data )*, ( %SOURCE_REFERENCE; )?, ( comment | klv-data )* )>
<!ATTLIST comment-marker
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    position CDATA #IMPLIED
>

<!ELEMENT descriptive-marker ( ( comment | klv-data )*, ( ( ( %SOURCE_REFERENCE; )?, ( comment | klv-data )*, descriptive-framework? ) | ( descriptive-framework?, ( comment | klv-data )*, ( %SOURCE_REFERENCE; )? ) ), ( comment | klv-data )* )>
<!ATTLIST descriptive-marker
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    position CDATA #IMPLIED
>

<!-- Type D components -->

<!--
    Operation Groups:
        In Specification:
            Contain 1 SourceReference (pre-rendered version)
            n Parameters
            m Segments
        In XML:
            Contain 1 Segment
-->

<!ELEMENT operation-group ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST operation-group
    track-type ( %ESSENCE_TYPE; ) #REQUIRED
    length CDATA #IMPLIED
    operation-definition CDATA #REQUIRED
>

<!ELEMENT video-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-dissolve
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT smpte-video-wipe ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST smpte-video-wipe
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-speed-control ( %COMMENTS_AND_COMPONENTS;, ( constant-speed-ratio | varying-speed-ratio )?, %COMMENTS_AND_COMPONENTS; )>
<!ATTLIST video-speed-control
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

    <!ELEMENT constant-speed-ratio EMPTY>
    <!ATTLIST constant-speed-ratio
        numerator CDATA #REQUIRED
        denominator CDATA #REQUIRED
    >

    <!ELEMENT varying-speed-ratio EMPTY>
    <!ATTLIST varying-speed-ratio
        numerator CDATA #REQUIRED
        denominator CDATA #REQUIRED
        interpolator ( b-spline | constant | linear | log | none | power ) #REQUIRED
    >

<!ELEMENT video-repeat ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-repeat
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-flip ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flip
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-flop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flop
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-flip-flop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-flip-flop
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-position ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-position
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-crop ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-crop
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-scale ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-scale
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-rotate ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-rotate
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT video-corner-pinning ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST video-corner-pinning
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT alpha-with-video-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST alpha-with-video-key
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT separate-alpha-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST separate-alpha-key
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT luminance-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST luminance-key
    track-type ( picture ) #REQUIRED
    length CDATA #REQUIRED
>

<!ELEMENT chroma-key ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST chroma-key
    track-type ( picture ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT mono-audio-gain ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-gain
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT mono-audio-pan ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-pan
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT mono-audio-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST mono-audio-dissolve
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!ELEMENT two-parameter-mono-audio-dissolve ( %COMMENTS_AND_SEGMENTS; )>
<!ATTLIST two-parameter-mono-audio-dissolve
    track-type ( audio ) #REQUIRED
    length CDATA #IMPLIED
>

<!-- Mob Slots -->

<!ELEMENT timeline-mob-slot ( %SEGMENT; )>
<!ATTLIST timeline-mob-slot
    edit-rate-numerator CDATA #REQUIRED
    edit-rate-denominator CDATA #REQUIRED
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
    marked-in-point CDATA #IMPLIED
    marked-out-point CDATA #IMPLIED
    origin CDATA #IMPLIED
>

<!ELEMENT static-mob-slot ( %SEGMENT; )>
<!ATTLIST static-mob-slot
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!ELEMENT event-mob-slot ( %SEGMENT; )>
<!ATTLIST event-mob-slot
    edit-rate-numerator CDATA #REQUIRED
    edit-rate-denominator CDATA #REQUIRED
    name CDATA #IMPLIED
    physical-track-number CDATA #IMPLIED
>

<!-- Other Interchange Objects -->
<!ELEMENT descriptive-framework EMPTY>

<!-- End a derivation chain on a mob -->
<!ELEMENT bad-eoc EMPTY>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPAnnotationTest2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file>
<!-- This test is the same as EPAnnotationTest, but, does not have any
         dictionary entries so it should result in extra failures -->
<!-- Test UserComments property -->
 <top-level name="User Comments in Mob Slot Segment">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <source-clip length="0" track-type="none">
    <comment value="Should Pass" name="Test Case 1"/>
    <lower-level>
     <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
      <eoc length="0" track-type="none"/>
     </timeline-mob-slot>
    </lower-level>
   </source-clip>
  </timeline-mob-slot>
 </top-level>
 <top-level name="User Comments in CommentMarker">
  <event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="none">
    <comment-marker track-type="none" length="1">
     <comment value="Should Pass" name="Test Case 2"/>
    </comment-marker>
   </sequence>
  </event-mob-slot>
 </top-level>
<!-- NOTE: Currently this test case is not causing an error because the
               comment is not in the dictionary.  This is occuring because
               the traversal ends when a UserComment is detected in the second
               sequence.  If the traversal is made to continue, this test case
               will fail -->
 <top-level name="Illegal User Comments">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="none">
    <sequence track-type="none"  length="1">
     <comment value="Should Fail" name="Test Case 3"/>
     <eoc track-type="none" length="1"/>
    </sequence>
   </sequence>
  </timeline-mob-slot>
 </top-level>
<!-- Test CommentMarkes in essence/non-essence tracks -->
<!-- Note: Case 2 above tests CommentMarkers in non-essence tracks -->
 <top-level name="CommentMarker in Essence Track">
  <event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <comment-marker track-type="audio" length="1"/>
   </sequence>
  </event-mob-slot>
 </top-level>
 <top-level name="DescriptiveMarker in Essence Track">
  <event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <descriptive-marker track-type="audio" length="1"/>
   </sequence>
  </event-mob-slot>
 </top-level>
<!-- NEED TO TEST A DESCRIPTIVE MARKER IN AN ESSENCE TRACK -->
<!-- Test CommentMarkes in Mob Slots (and nested in mob slots) -->
<!-- Note: "CommentMarker in Essence Track" above test tests nested in an event mob slot -->
 <top-level name="CommentMarker in Event Mob Slot">
  <event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <comment-marker length="0" track-type="none"/>
  </event-mob-slot>
 </top-level>
 <top-level name="CommentMarker nested in Timeline Mob Slot">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="none">
    <comment-marker length="0" track-type="none"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="CommentMarker in Timeline Mob Slot">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <comment-marker length="0" track-type="none"/>
  </timeline-mob-slot>
 </top-level>
 <top-level name="CommentMarker nested in Static Mob Slot">
  <static-mob-slot>
   <sequence length="0" track-type="none">
    <comment-marker length="0" track-type="none"/>
   </sequence>
  </static-mob-slot>
 </top-level>
 <top-level name="CommentMarker in Static Mob Slot">
  <static-mob-slot>
   <comment-marker length="0" track-type="none"/>
  </static-mob-slot>
 </top-level>
<!-- Note: "DescriptiveMarker in Essence Track" above test tests nested in an event mob slot -->
 <top-level name="DescriptiveMarker in Event Mob Slot">
  <event-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <descriptive-marker length="0" track-type="none"/>
  </event-mob-slot>
 </top-level>
 <top-level name="DescriptiveMarker nested in Timeline Mob Slot">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="none">
    <descriptive-marker track-type="none" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="DescriptiveMarker in Timeline Mob Slot">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <descriptive-marker length="0" track-type="none"/>
  </timeline-mob-slot>
 </top-level>
 <top-level name="DescriptiveMarker nested in Static Mob Slot">
  <static-mob-slot>
   <sequence length="0" track-type="none">
    <descriptive-marker track-type="none" length="1"/>
   </sequence>
  </static-mob-slot>
 </top-level>
 <top-level name="DescriptiveMarker in Static Mob Slot">
  <static-mob-slot>
   <descriptive-marker length="0" track-type="none"/>
  </static-mob-slot>
 </top-level>
<!-- Test a registered KLV Data -->
 <top-level name="Registered KLV Data">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <klv-data value="Should Pass" key-name="KLV Test"/>
    <eoc track-type="audio" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
</aaf-file>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPMultiChannelAudioTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file>
 <top-level>
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <source-clip length="0" track-type="audio">
    <clip>
     <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
      <source-clip length="0" track-type="audio">
       <mono-audio name="Mono Audio in Composition and Master" sample-rate-denominator="1" sample-rate-numerator="1">
        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
         <eoc length="0" track-type="audio"/>
        </timeline-mob-slot>
       </mono-audio>
      </source-clip>
     </timeline-mob-slot>
    </clip>
   </source-clip>
  </timeline-mob-slot>
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <source-clip length="0" track-type="audio">
    <clip>
     <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
      <source-clip length="0" track-type="audio">
       <multi-channel-audio name="Multi-Channel Audio in Composition and Master" sample-rate-denominator="1" sample-rate-numerator="1">
        <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
         <eoc length="0" track-type="audio"/>
        </timeline-mob-slot>
       </multi-channel-audio>
      </source-clip>
     </timeline-mob-slot>
    </clip>
   </source-clip>
  </timeline-mob-slot>
 </top-level>
</aaf-file>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPParameterTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file operational-pattern="invalid">
<!-- Make sure all and only valid interpolators are accepted -->
 <top-level name="None Interpolator">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <video-speed-control length="0" track-type="picture">
    <varying-speed-ratio interpolator="none" denominator="1" numerator="1"/>
   </video-speed-control>
  </timeline-mob-slot>
 </top-level>
 <top-level name="B-Spline Interpolator">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <video-speed-control length="0" track-type="picture">
    <varying-speed-ratio interpolator="b-spline" denominator="1" numerator="1"/>
   </video-speed-control>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Constant Interpolator">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <video-speed-control length="0" track-type="picture">
    <varying-speed-ratio interpolator="constant" denominator="1" numerator="1"/>
   </video-speed-control>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Linear Interpolator">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <video-speed-control length="0" track-type="picture">
    <varying-speed-ratio interpolator="linear" denominator="1" numerator="1"/>
   </video-speed-control>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Log Interpolator">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <video-speed-control length="0" track-type="picture">
    <varying-speed-ratio interpolator="log" denominator="1" numerator="1"/>
   </video-speed-control>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Power Interpolator">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <video-speed-control length="0" track-type="picture">
    <varying-speed-ratio interpolator="power" denominator="1" numerator="1"/>
   </video-speed-control>
  </timeline-mob-slot>
 </top-level>
</aaf-file>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPDefinitionTest2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file effect-data-definitions="legacy">
<!-- Test every operation defined in the edit protocol with legacy Data
       Definition values -->
 <top-level name="Video Dissolve not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-dissolve track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="SMPTE Video Wipe not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <smpte-video-wipe track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Speed Control not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-speed-control track-type="picture" length="1">
     <constant-speed-ratio denominator="1" numerator="1"/>
    </video-speed-control>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Repeat not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-repeat track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Flip not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-flip track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Flop not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-flop track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Flip-Flop not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-flip-flop track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Position not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-position track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Crop not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-crop track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Scale not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-scale track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Rotate not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-rotate track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Video Corner Pinning not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <video-corner-pinning track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Alpha With Video Key not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <alpha-with-video-key track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Separate Alpha Key not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <separate-alpha-key track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Luminance Key not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <luminance-key track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Chroma Key not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="picture">
    <eoc track-type="picture" length="1"/>
    <chroma-key track-type="picture" length="1"/>
    <eoc track-type="picture" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Mono Audio Gain not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <eoc track-type="audio" length="1"/>
    <mono-audio-gain track-type="audio" length="1"/>
    <eoc track-type="audio" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Mono Audio Pan not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <eoc track-type="audio" length="1"/>
    <mono-audio-pan track-type="audio" length="1"/>
    <eoc track-type="audio" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Mono Audio Dissolve not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <eoc track-type="audio" length="1"/>
    <mono-audio-dissolve track-type="audio" length="1"/>
    <eoc track-type="audio" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
 <top-level name="Two Parameter Mobo Audio Dissolve not in Transition">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <sequence length="0" track-type="audio">
    <eoc track-type="audio" length="1"/>
    <two-parameter-mono-audio-dissolve track-type="audio" length="1"/>
    <eoc track-type="audio" length="1"/>
   </sequence>
  </timeline-mob-slot>
 </top-level>
</aaf-file>

=== jhliberty/AAF/Utilities/AAFAnalyzer/RegressionTest/TestFiles/EPDerivationTest4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aaf-file SYSTEM "EPDerivationChain.dtd">
<aaf-file>
<!-- Master->TopLevel test REQ_EP_025.2. The Master->TopLevel should
      fail without invoking the derivatino chain parser because it
      will be detected as a top level composition that is referenced
      by on or more clips. We use a master to reference the top level
      because specifically don't it to be ignored by the derivation
      chain parser. -->
 <clip name="Master->TopLevel">
  <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
   <source-clip length="0" track-type="none">
    <top-level name="Master->Top-Level">
     <timeline-mob-slot edit-rate-denominator="1" edit-rate-numerator="1">
      <eoc length="0" track-type="none"/>
     </timeline-mob-slot>
    </top-level>
   </source-clip>
  </timeline-mob-slot>
 </clip>
<!-- Test with static mob slots. The code should have no dependency on
 mob slot type. This is intended to confirm that. -->
 <top-level name="top level composition with reference to static essence">
  <timeline-mob-slot edit-rate-numerator="30000" edit-rate-denominator="1001">
   <sequence length="1">
    <source-clip length="1">
     <clip name="clip with reference to static essence">
      <static-mob-slot edit-rate-numerator="30000" edit-rate-denominator="1001">
       <source-clip length="1">
        <rgba-source sample-rate-denominator="30000" sample-rate-numerator="1001">
         <static-mob-slot name="Static stlot included in derivation chain and referenced from timeline.">
          <eoc/>
         </static-mob-slot>
        </rgba-source>
       </source-clip>
      </static-mob-slot>
     </clip>
    </source-clip>
   </sequence>
  </timeline-mob-slot>
 </top-level>
</aaf-file>
